### ISSUE TITLE
Missing Segmentations

### ISSUE THREAD

**Issue by TaWald** [neheller/kits19#58]
Hello,

there are Segmentations missing in the data folder.
171 and 204 don't have a segmentation in the repo, therefore the downloader can't grab them and leaves 2 train images unlabeled.
Would be much appreciated if you could add them again :)

**Comment by TaWald** [comment]
To specify this some more:
When downloading the data with get_imaging.py i can't seem to download the segmentations of case_00171 and case_00204. 
I tried to reissue the command after deleting the case_00171 and case_00204 multiple times but only the images are downloaded and no corresponding segmentations. For the rest of the cases this works fine though.

**Comment by neheller** [comment]
Sorry you're experiencing this. After a quick check I can't seem to find what the problem is... the segmentations for 171 and 204 seem to be in their correct locations ([here](https://github.com/neheller/kits19/tree/master/data/case_00171) and [here](https://github.com/neheller/kits19/tree/master/data/case_00204), respectively) and I tried running `get_imaging` just now and it grabbed the imaging for these two without issue.

Which branch are you working in? When did you clone/last pull?

**Comment by TaWald** [comment]
I think I messed up :)
Due to single files not downloading completely I had deleted the folder instead of only the imaging file to reissue the download.
I actually (wrongly) assumed at that time, it downloads image label pairs however it only downloads the images and the segmentations are getting cloned.
Sorry to bother you with that ...
